adminpanel/urls.py
from . import views
from django.urls import path

app_name = 'adminpanel'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('work/', views.work, name='work'),
    path('about_contact/', views.about_contact, name='about_contact'),
    path('edit_about/', views.edit_about, name='edit_about'),
    path('delete_file/<int:file_id>/', views.delete_file, name='delete_file'),
    path('delete_file_bottom/<int:file_id>/', views.delete_file_bottom, name='delete_file_bottom'),
    path('delete_file_work/<int:file_id>/', views.delete_file_work, name='delete_file_work'),
    path('add_project/', views.add_project, name='add_project'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('edit_project/<int:project_id>/', views.edit_project, name='edit_project'),
    path('edit_work_project/<int:project_id>/', views.edit_work_project, name='edit_work_project'),
    path('delete_project/<int:project_id>/', views.delete_project, name='delete_project'),
    path('delete_work_project/<int:project_id>/', views.delete_work_project, name='delete_work_project'),
    path('addbottom_projects/', views.add_bottom_project, name='addbottom_projects'),
    path('edit_bottom_project/<int:bottom_id>/', views.edit_bottom_project, name='edit_bottom_project'),
    path('delete-bottom-project/<int:bottom_id>/', views.delete_bottom_project, name='delete_bottom_project'),

]

portfolio/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("user.urls")),
    path("adminpanel/", include("adminpanel.urls")),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = 'user.views.error_404_view'

user/urls.py
from . import views
from django.urls import path

app_name = 'user'

urlpatterns = [
    path('', views.userhome, name='userhome'),
    path('project_detail/<int:project_id>/', views.project_detail, name='project_detail'),
    path('moreworks/<int:bottom_id>/', views.moreworks, name='moreworks'),
    path('worklist/', views.worklist, name='worklist'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),


]

adminpanel/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    def __str__(self):
        return self.name
    
    
    
class HomepageProject(models.Model):
    project_name = models.CharField(max_length=255)
    keyword = models.CharField(max_length=255)
    description = models.TextField()
    hover_img = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    year = models.PositiveIntegerField(blank=True, null=True) 
    company = models.CharField(blank=True, null=True,max_length=255) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.project_name    
    
    
    

class HomeProjectFile(models.Model):
    project = models.ForeignKey(HomepageProject, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='homepage_projects/videos/',max_length=500)
    
    def __str__(self):
        return f'File for {self.project.project_name}'    
    


class WorkpageProject(models.Model):
    project_name = models.CharField(max_length=255)
    keyword = models.CharField(max_length=255)
    description = models.TextField()
    hover_img = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    year = models.PositiveIntegerField(blank=True, null=True) 
    company = models.CharField(blank=True, null=True,max_length=255) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.project_name

class ProjectFile(models.Model):
    project = models.ForeignKey(WorkpageProject, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='homepage_projects/videos/',max_length=500)
    
    def __str__(self):
        return f'File for {self.project.project_name}'
    
    
    
class BottomProject(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    hover_img = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    def __str__(self):
        return self.name    
    
class BottomProjectFile(models.Model):
    project = models.ForeignKey(BottomProject, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='bottom_projects/file/')
    
    def __str__(self):
        return f'File for {self.project.name}'
    
    
class About(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    about_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    contact_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    name = models.CharField(max_length=100) 
    subdescription = models.CharField(max_length=255, blank=True, null=True)  
    maindescription = models.TextField(blank=True, null=True)  
    references = models.TextField(blank=True, null=True)  
    email = models.EmailField(max_length=100, blank=True, null=True)  
    whatsapp = models.CharField(max_length=15, blank=True, null=True)  

    def __str__(self):
        return self.name  

    
    

adminpanel/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import About, BottomProject, BottomProjectFile, HomeProjectFile, ProjectFile, UserProfile, WorkpageProject
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from .models import HomepageProject
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import SuspiciousFileOperation

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password) 
        
        if user is not None:
            if user.is_superuser:  
                auth_login(request, user)
                return redirect('adminpanel:index')
            else:
                messages.error(request, 'Access denied. Superuser privileges are required.')
        else:
            messages.error(request, 'Invalid credentials')
            
    return render(request, 'adminpanel/login.html')

@login_required
def index(request):
    return render(request, 'adminpanel/index.html')

@login_required
def home(request):
    last_profile = UserProfile.objects.order_by('-id').first()
    projects = HomepageProject.objects.all().prefetch_related('files')
    bottomprojects = BottomProject.objects.all().prefetch_related('files')

    for project in projects:
        project.keywords_list = [keyword.strip() for keyword in project.keyword.split(',')] if project.keyword else []
        project.files_data = [
            {
                'id': file.id,
                'url': file.file.url if file.file else '',
                'is_video': file.file.url.endswith('.mp4') if file.file else False
            }
            for file in project.files.all()
        ]

    for bottom in bottomprojects:
        bottom.files_data = [
            {
                'id': file.id,
                'url': file.file.url if file.file else '',
                'is_video': file.file.url.endswith('.mp4') if file.file else False
            }
            for file in bottom.files.all()
        ]

    context = {
        'profile': last_profile,
        'projects': projects,
        'bottomprojects': bottomprojects  
    }

    return render(request, 'adminpanel/home.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        if 'edit_profile' in request.POST:
            profile = UserProfile.objects.get(user=request.user)
            profile.name = request.POST.get('name')
            profile.description = request.POST.get('description')
            if request.FILES.get('image'):
                profile.profile_image = request.FILES['image']
            profile.save()  
            return redirect('adminpanel:home')  


@login_required
def add_project(request):
    if request.method == 'POST':
        project_name = request.POST.get('projectName')
        keyword = request.POST.get('keyword')
        description = request.POST.get('description')
        year = request.POST.get('year')
        company = request.POST.get('company')
        hover_img = request.FILES.get('image')  
        my_files = request.FILES.getlist('my_files') 
        year_value = int(year) if year else None

        errors = []
        if not project_name:
            errors.append("Project name is required.")
        if not description:
            errors.append("Description is required.")  
        if not hover_img:
            errors.append("Hover image is required.")
        if not my_files:
            errors.append("At least one file must be uploaded.")   
              
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('adminpanel:home')
        
        # Attempt to save the project and files
        try:
            project = HomepageProject(
                project_name=project_name,
                keyword=keyword,
                description=description,
                year=year_value,
                company=company,
                hover_img=hover_img  
            )
            project.save()  

            for file in my_files:
                # Try to create a file entry for each file
                HomeProjectFile.objects.create(
                    project=project,
                    file=file
                )

            messages.success(request, "Project added successfully!")
            return redirect('adminpanel:home')  

        except SuspiciousFileOperation:
            messages.error(request, "One or more files have a filename that is too long. Please rename the files and try again.")
            return redirect('adminpanel:home')

    return render(request, 'adminpanel/home.html')


@login_required
def edit_project(request, project_id):
    project = get_object_or_404(HomepageProject, id=project_id)
    
    if request.method == 'POST':
        project.project_name = request.POST.get('project_name')
        project.keyword = request.POST.get('keyword')
        project.description = request.POST.get('description')
        year = request.POST.get('year')
        project.year = int(year) if year and year.lower() != 'none' else None

        if request.FILES.get('hover_img'):
            project.hover_img = request.FILES.get('hover_img')

        project.save()

        files = request.FILES.getlist('my_files')
        for f in files:
            HomeProjectFile.objects.create(project=project, file=f)

        messages.success(request, 'Project updated successfully!')
        return redirect('adminpanel:home')
    
    return render(request, 'adminpanel/home.html')


@login_required
def delete_project(request, project_id):
    project = get_object_or_404(HomepageProject, id=project_id)
    project.delete()
    messages.success(request, 'Project deleted successfully!')
    return redirect('adminpanel:home')


@csrf_exempt 
@login_required
def delete_file(request, file_id):
    if request.method == 'POST':
        file = get_object_or_404(HomeProjectFile, id=file_id)
        file.delete()
        return JsonResponse({"success": True, "message": "File deleted successfully."})
    return JsonResponse({"success": False, "message": "Invalid request method."})

@csrf_exempt 
@login_required
def delete_file_bottom(request, file_id):
    if request.method == 'POST':
        file = get_object_or_404(BottomProjectFile, id=file_id)
        file.delete()
        return JsonResponse({"success": True, "message": "File deleted successfully."})
    return JsonResponse({"success": False, "message": "Invalid request method."})


# starting work page logic

@login_required
def work(request):
    if request.method == 'POST':
        project_name = request.POST.get('projectName')
        keyword = request.POST.get('keyword')
        description = request.POST.get('description')
        year = request.POST.get('year')
        hover_img = request.FILES.get('image')  
        my_files = request.FILES.getlist('my_files') 
        company = request.POST.get('company')
        year_value = int(year) if year else None
        
        errors = []
        if not project_name:
            errors.append("Project name is required.")
        if not description:
            errors.append("Description is required.")  
        if not my_files:
            errors.append("At least one file must be uploaded.")   
              
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('adminpanel:work')
        try:
            project = WorkpageProject(
                project_name=project_name,
                keyword=keyword,
                description=description,
                year=year_value,
                hover_img=hover_img,
                company=company,
    
            )
            project.save()  
            for file in my_files:
                ProjectFile.objects.create(
                    project=project,
                    file=file
                )
            messages.success(request, "Project added successfully!")
            return redirect('adminpanel:work')  
        except SuspiciousFileOperation:
            messages.error(request, "One or more files have a filename that is too long. Please rename the files and try again.")
            return redirect('adminpanel:work')
   
    projects = WorkpageProject.objects.all().prefetch_related('files')

    for project in projects:
        project.keywords_list = [keyword.strip() for keyword in project.keyword.split(',')] if project.keyword else []
        
        project.files_data = [
            {
                'id': file.id,
                'url': file.file.url if file.file else '',
                'is_video': file.file.name.endswith('.mp4') if file.file else False
            }
            for file in project.files.all()
        ]

    context = {
        'projects': projects
    }
    return render(request, 'adminpanel/work.html', context)

@csrf_exempt 
@login_required
def delete_file_work(request, file_id):
    if request.method == 'POST':
        file = get_object_or_404(ProjectFile, id=file_id)
        file.delete()
        return JsonResponse({"success": True, "message": "File deleted successfully."})
    return JsonResponse({"success": False, "message": "Invalid request method."})


@login_required
def edit_work_project(request, project_id):
    project = get_object_or_404(WorkpageProject, id=project_id)
    
    if request.method == 'POST':
        project.project_name = request.POST.get('project_name')
        project.keyword = request.POST.get('keyword')
        project.description = request.POST.get('description')
        project.year = request.POST.get('year')

        if request.FILES.get('hover_img'):

templates/adminpanel/about_contact.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>About and Contact</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/adminhome.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        .custom-profile-card {
            border: 1px solid #dee2e6;
            border-radius: 8px;
            box-shadow: 0px 6px 12px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }
        
        .profile-image, .contact-image {
            width: 100%;
            height: auto;
            object-fit: cover;
            border-radius: 8px;
        }

        .profile-details {
            padding: 20px;
        }

        .profile-name {
            font-size: 1.8rem;
            font-weight: bold;
            color: #343a40;
        }

        .profile-subdescription, .profile-maindescription, .profile-references, 
        .profile-email, .profile-whatsapp {
            font-size: 1rem;
            color: #6c757d;
        }

        .edit-button-container {
            margin-top: 15px;
        }

        .edit-button-container .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
        }
                
    </style>
</head>

<body>
    <section>
      <div class="container mt-5">
        <h1 class="text-center mb-4">About and Contact Page</h1>

          <!-- User Card -->
          <div class="custom-profile-card">
              <div class="row no-gutters">
                  <!-- Profile Image Section -->
                  <div class="col-md-4">
                      {% if about.about_image %}
                      <img src="{{ about.about_image.url }}" class="profile-image" alt="{{ about.name }}'s profile image" /> 
                      {% endif %}
                  </div>
                  <!-- Contact Image Section -->
                  <div class="col-md-4">
                      {% if about.contact_image %}
                      <img src="{{ about.contact_image.url }}" class="contact-image" alt="{{ about.name }}'s contact image" /> 
                      {% endif %}
                  </div>
                  <div class="col-md-8">
                      <div class="profile-details">
                          <h1 class="profile-name">{{ about.name }}</h1>
                          <p class="profile-subdescription">{{ about.subdescription }}</p>
                          <hr/>
                          <p class="profile-maindescription">{{ about.maindescription }}</p>
                          <hr/>
                          <p class="profile-references">{{ about.references }}</p>
                          <hr/>
                          <p class="profile-email">{{ about.email }}</p>
                          <hr/>
                          <p class="profile-whatsapp">{{ about.whatsapp }}</p>
                          <hr/>
                          <div class="edit-button-container">
                              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editProfileModal">
                                  Edit Profile
                              </button>
                          </div>
                      </div>
                  </div>
              </div>
          </div>

          <!-- Profile Edit Modal -->
          <div class="modal fade" id="editProfileModal" tabindex="-1" role="dialog" aria-labelledby="editProfileModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                  <div class="modal-content">
                      <div class="modal-header">
                          <h5 class="modal-title" id="editProfileModalLabel">Edit Profile</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                      <div class="modal-body">
                          <form method="post" enctype="multipart/form-data" action="{% url 'adminpanel:edit_about' %}">
                              {% csrf_token %}
                              <div class="form-group">
                                  <label for="name">Name</label>
                                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter your name" value="{{ about.name }}" required />
                              </div>
                              <div class="form-group">
                                  <label for="subdescription">Sub-description</label>
                                  <textarea name="subdescription" class="form-control" id="subdescription" rows="2" placeholder="Enter a short sub-description" required>{{ about.subdescription }}</textarea>
                              </div>
                              <div class="form-group">
                                  <label for="maindescription">Main Description</label>
                                  <textarea name="maindescription" class="form-control" id="maindescription" rows="4" placeholder="Enter a detailed description" required>{{ about.maindescription }}</textarea>
                              </div>
                              <div class="form-group">
                                  <label for="references">References</label>
                                  <textarea name="references" class="form-control" id="references" rows="2" placeholder="Enter references">{{ about.references }}</textarea>
                              </div>
                              <div class="form-group">
                                  <label for="email">Email</label>
                                  <input type="email" name="email" class="form-control" id="email" placeholder="Enter your email" value="{{ about.email }}" required />
                              </div>
                              <div class="form-group">
                                  <label for="whatsapp">WhatsApp</label>
                                  <input type="text" name="whatsapp" class="form-control" id="whatsapp" placeholder="Enter WhatsApp number" value="{{ about.whatsapp }}" />
                              </div>
                              <div class="form-group">
                                  <label for="image">About Image</label>
                                  <input type="file" accept="image/png, image/jpeg, image/jpg" name="image" class="form-control-file" />
                              </div>
                              <div class="form-group">
                                  <label for="contactimage">Contact Image</label>
                                  <input type="file" accept="image/png, image/jpeg, image/jpg" name="contactimage" class="form-control-file" />
                              </div>
                              <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                      Close
                                  </button>
                                  <button type="submit" name="edit_profile" class="btn btn-primary">
                                      Save changes
                                  </button>
                              </div>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
          
      </div>    
    </section>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/adminpanel/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="./images/favicon-32x32.png"
    />

    <title>Akbar Admin-panel</title>
    <link rel="stylesheet" href="styles.css" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,600;1,200;1,400;1,600&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/adminpanelhome.css' %}"
    />
  </head>

  <body>
    <div class="header">
      <h1>Akbar Portfolio</h1>
      <p>
        Update your portfolio images and content to give your website a fresh
        look and improve its smoothness and functionality for a better user
        experience.
      </p>
    </div>

    <div class="row1-container">
      <!-- Home Page Box -->

        <div class="box box-down cyan" data-url={% url 'adminpanel:home' %}>
          <h2>Home Page</h2>
          <p>
            Revamp your homepage to create a more engaging and user-friendly
            experience.
          </p>
          <img
            src="https://assets.codepen.io/2301174/icon-supervisor.svg"
            alt=""
          />
        </div>

      <!-- Work Page Box -->
      <div class="box red" data-url={% url 'adminpanel:work' %}>
        <h2>Work Page</h2>
        <p>
          Add your work and edit easily to create the optimal team for your
          project.
        </p>
        <img
          src="https://assets.codepen.io/2301174/icon-team-builder.svg"
          alt=""
        />
      </div>

      <div class="box box-down cyan" data-url={% url 'adminpanel:about_contact' %}>
        <h2>About and Contact Page</h2>
        <p>
          Revamp your homepage to create a more engaging and user-friendly
          experience.
        </p>
        <img
          src="https://assets.codepen.io/2301174/icon-supervisor.svg"
          alt=""
        />
      </div>
    </div>

    <script>
      // JavaScript for navigation on card click
      document.querySelectorAll(".box").forEach((card) => {
        card.addEventListener("click", () => {
          const url = card.getAttribute("data-url");
          window.open(url, "_blank");
        });
      });
    </script>
  </body>
</html>

templates/adminpanel/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400,300,600" rel="stylesheet">
    <style>
        * {
            box-sizing: border-box;
        }

        body {
            font-family: 'open sans', helvetica, arial, sans-serif;
            background: url(http://farm8.staticflickr.com/7064/6858179818_5d652f531c_h.jpg) no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
        }

        .log-form {
            width: 40%;
            min-width: 320px;
            max-width: 475px;
            background: #fff;
            position: absolute;
            top: 50%;
            left: 50%;
            -webkit-transform: translate(-50%, -50%);
            -moz-transform: translate(-50%, -50%);
            -o-transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
            box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.25);
        }

        @media (max-width: 40em) {
            .log-form {
                width: 95%;
                position: relative;
                margin: 2.5% auto 0 auto;
                left: 0%;
                -webkit-transform: translate(0%, 0%);
                -moz-transform: translate(0%, 0%);
                -o-transform: translate(0%, 0%);
                -ms-transform: translate(0%, 0%);
                transform: translate(0%, 0%);
            }
        }

        .log-form form {
            display: block;
            width: 100%;
            padding: 2em;
        }

        .log-form h2 {
            width: 100%;
            color: #545454;
            font-family: 'open sans condensed';
            font-size: 1.35em;
            display: block;
            background: #2a2a2a;
            width: 100%;
            text-transform: uppercase;
            padding: .75em 1em .75em 1.5em;
            box-shadow: inset 0px 1px 1px rgba(255, 255, 255, 0.05);
            border: 1px solid #232323;
            margin: 0;
            font-weight: 200;
        }

        .log-form input {
            display: block;
            margin: auto auto;
            width: 100%;
            margin-bottom: 2em;
            padding: .5em 0;
            border: none;
            border-bottom: 1px solid #eaeaea;
            padding-bottom: 1.25em;
            color: #757575;
        }

        .log-form input:focus {
            outline: none;
        }

        .log-form .btn {
            display: inline-block;
            background: #1fb5bf;
            border: 1px solid #1ba6af;
            padding: .5em 2em;
            color: white;
            margin-right: .5em;
            box-shadow: inset 0px 1px 0px rgba(255, 255, 255, 0.2);
        }

        .log-form .btn:hover {
            background: #23c2cd;
        }

        .log-form .btn:active {
            background: #1fb5bf;
            box-shadow: inset 0px 1px 1px rgba(0, 0, 0, 0.1);
        }

        .log-form .btn:focus {
            outline: none;
        }

        .log-form .forgot {
            color: #30c4cf;
            line-height: .5em;
            position: relative;
            top: 2.5em;
            text-decoration: none;
            font-size: .75em;
            margin: 0;
            padding: 0;
            float: right;
        }

        .log-form .forgot:hover {
            color: #1ba6af;
        }
    </style>
</head>
<body>
    <div class="log-form">
        <h2>Login to your account</h2>
        <form method="POST" action="{% url 'adminpanel:login' %}">
            {% csrf_token %}
            <input type="text" name="username" title="username" placeholder="username" required />
            <input type="password" name="password" title="password" placeholder="password" required />
            <button type="submit" class="btn">Login</button>
        </form>
    </div>
</body>
</html>